### ISSUE TITLE
GrSwig error when building for GNU Radio 3.9.2.0 

### ISSUE THREAD

**Issue by kurtulmehtap** [dkozel/gr-latency_manager#2]
- Build type not specified: defaulting to release.
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
-- User set python executable /usr/bin/python3
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found suitable exact version "3.8.10") 
-- Extracting version information from git describe...
-- Using install prefix: /usr/local
-- Building for version: 468e6d1a / 1.0.0git
-- No C++ unit tests... skipping
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.10") 
CMake Error at swig/CMakeLists.txt:37 (include):
  include could not find load file:

    GrSwig

CMake Error at swig/CMakeLists.txt:51 (GR_SWIG_MAKE):
  Unknown CMake command "GR_SWIG_MAKE".

-- Configuring incomplete, errors occurred!
See also "/home/rftest/gr-workinprogress/build/CMakeFiles/CMakeOutput.log".
See also "/home/rftest/gr-workinprogress/build/CMakeFiles/CMakeError.log".

**Comment by dkozel** [comment]
Hi @kurtulmehtap I have not updated this project publicly for GNU Radio 3.9. Which blocks are you interested in? I have some of them updated.

**Comment by kurtulmehtap** [comment]
CMakeLists.txt says 
find_package(Gnuradio "3.9" REQUIRED), so I thought It was for 3.9.
It seems like a general problem as it asks for the already installed swig during cmake.
In particular; We need the components used for the latency reduction as described in GRCon19 - Managing Latency in Continuous GNU Radio Flowgraphs by Matt Ettus

**Comment by dkozel** [comment]
The code was developed after 3.8 was released but before 3.9 was finalized, so there are no release versions of GNU Radio that this code currently runs on. I have updated the polarization conversion blocks in a separate repository, but haven't updated the Latency Manager blocks yet. It's been on my todo list for a while and I don't know when I'll have a chance to do them myself. The steps needed are here:
https://wiki.gnuradio.org/index.php/GNU_Radio_3.9_OOT_Module_Porting_Guide

I'll try and update it this weekend if I have extra time. If you need it urgently and can do the updates please do submit a pull request and I'll test and merge it.

**Comment by dkozel** [comment]
The code is now updated and consistent for GNU Radio 3.10. Hopefully that will work for most people's use-cases. If anyone does backport it to 3.8/9 I'd be happy to merge that to a maint branch.
